services:
  mongodb:
    image: mongo:7.0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb-local-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "quit(db.adminCommand('ping').ok ? 0 : 2)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.2-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-local-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongodb-local-data:
  redis-local-data:
