spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: tosunsaeng-db
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}

  servlet:
    multipart:
      max-file-size: 10MB      # 파일 하나당 최대 크기 (필요 시 20MB 등으로 늘리세요)
      max-request-size: 10MB   # 요청 하나당 최대 크기

jwt:
  secret: ${JWT_SECRET_KEY:ThisIsATemporarySecretKeyForTosunsaengProject2026!@#}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
  tomcat:
    threads:
      max: 20       # 최대 톰캣 스레드 수 제한 (프리티어 메모리 폭발 방지)
      min-spare: 4  # 최소 대기 스레드 수
    max-connections: 100 # 동시에 허용할 최대 커넥션 수